/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "custom.h"
#include "user_serial.h"
#include "ctrl_serial.h"
#include "ui_objects.h"
#include <rtthread.h>

void switch_event_cb(lv_event_t *e)
{
    lv_obj_t *sw = lv_event_get_target(e);
    int state = lv_obj_has_state(sw, LV_STATE_CHECKED) ? 1 : 0;
    int device_id = (int)(intptr_t)lv_event_get_user_data(e);

    rt_kprintf("Switch %d state changed to %d\n", device_id, state);
    ctrl_send_switch_state(device_id, state);
}

static void ui_update_timer_cb(lv_timer_t *timer)
{
    update_ui_display();
}

void custom_init()
{
    ctrl_serial_init();
    uart3_serial_init();
    lv_timer_create(ui_update_timer_cb, 100, NULL);
}
