/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"


static void screen_button_1_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create start_page
        start_page_create(&ui_manager);
        // load start_page
        lv_scr_load_anim(start_page_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, ui_manager.auto_del);
    }
}


void screen_create(ui_manager_t *ui)
{
    screen_t *scr = screen_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xfcfcfc), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_2
    scr->image_2 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_2, LVGL_IMAGE_PATH(screen2_480x270.png));
    lv_img_set_pivot(scr->image_2, 50, 50);
    lv_img_set_angle(scr->image_2, 0);
    lv_obj_set_style_img_opa(scr->image_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_2, 0, 0);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "温湿度：22℃/55%");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 83, 104);
    lv_obj_set_size(scr->label_1, 116, 14);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_droidsansfallback_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_2
    scr->label_2 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_2, "22/");
    lv_label_set_long_mode(scr->label_2, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_2, 108, 74);
    lv_obj_set_size(scr->label_2, 32, 18);

    // Set style of scr->label_2
    lv_obj_set_style_text_font(scr->label_2, fs_droidsansfallback_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_2, lv_color_hex(0x2844ff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "55%");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 137, 78);
    lv_obj_set_size(scr->label_3, 29, 18);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, fs_droidsansfallback_15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_3, lv_color_hex(0x2844ff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_4, "宠物体温：38.5℃");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 297, 104);
    lv_obj_set_size(scr->label_4, 116, 14);

    // Set style of scr->label_4
    lv_obj_set_style_text_font(scr->label_4, fs_droidsansfallback_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_5, "38.5℃");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 319, 74);
    lv_obj_set_size(scr->label_5, 64, 18);

    // Set style of scr->label_5
    lv_obj_set_style_text_font(scr->label_5, fs_droidsansfallback_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->label_5, lv_color_hex(0x2844ff), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_6
    scr->label_6 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_6, "缺水！请及时加水");
    lv_label_set_long_mode(scr->label_6, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_6, 83, 216);
    lv_obj_set_size(scr->label_6, 116, 14);

    // Set style of scr->label_6
    lv_obj_set_style_text_font(scr->label_6, fs_droidsansfallback_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_7
    scr->label_7 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_7, "大便次数：1");
    lv_label_set_long_mode(scr->label_7, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_7, 303, 216);
    lv_obj_set_size(scr->label_7, 91, 14);

    // Set style of scr->label_7
    lv_obj_set_style_text_font(scr->label_7, fs_droidsansfallback_13, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "返 回");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 217, 112);
    lv_obj_set_size(scr->button_1, 49, 49);

    // Set style of scr->button_1
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0xe2f3ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_droidsansfallback_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_1, lv_color_hex(0x151518), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, screen_button_1_clicked, LV_EVENT_CLICKED, NULL);


}


