/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_objects.h"
#include "aic_ui.h"
#include "ui_util.h"
#include "custom/custom.h"


static void start_page_button_1_clicked (lv_event_t *e) {
    lv_obj_t *act_scr = lv_scr_act();
    if (!screen_is_loading(act_scr)) {
        // delete child obj of act_scr
        lv_obj_clean(act_scr);
        // create screen
        screen_create(&ui_manager);
        // load screen
        lv_scr_load_anim(screen_get(&ui_manager)->obj, LV_SCR_LOAD_ANIM_NONE, 0, 0, ui_manager.auto_del);
    }
}


void start_page_create(ui_manager_t *ui)
{
    start_page_t *scr = start_page_get(ui);

    if (!ui->auto_del && scr->obj) {
        return;
    }

    // Init scr->obj
    scr->obj = lv_obj_create(NULL);
    lv_obj_set_scrollbar_mode(scr->obj, LV_SCROLLBAR_MODE_OFF);

    // Set style of scr->obj
    lv_obj_set_style_bg_color(scr->obj, lv_color_hex(0xebf3ff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(scr->obj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->image_1
    scr->image_1 = lv_img_create(scr->obj);
    lv_img_set_src(scr->image_1, LVGL_IMAGE_PATH(screen1_480x270.png));
    lv_img_set_pivot(scr->image_1, 50, 50);
    lv_img_set_angle(scr->image_1, 0);
    lv_obj_set_style_img_opa(scr->image_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_pos(scr->image_1, 0, 0);

    // Init scr->switch_1
    scr->switch_1 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_1, 163, 62);
    lv_obj_set_size(scr->switch_1, 50, 26);

    // Set style of scr->switch_1
    lv_obj_set_style_bg_color(scr->switch_1, lv_color_hex(0x8fc5fe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->switch_1, lv_color_hex(0xaaffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->switch_2
    scr->switch_2 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_2, 163, 140);
    lv_obj_set_size(scr->switch_2, 50, 26);

    // Set style of scr->switch_2
    lv_obj_set_style_bg_color(scr->switch_2, lv_color_hex(0x8fc7fe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->switch_2, lv_color_hex(0xaaffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->switch_3
    scr->switch_3 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_3, 355, 62);
    lv_obj_set_size(scr->switch_3, 50, 26);

    // Set style of scr->switch_3
    lv_obj_set_style_bg_color(scr->switch_3, lv_color_hex(0x8fc7fe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->switch_3, lv_color_hex(0xaaffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->switch_4
    scr->switch_4 = lv_switch_create(scr->obj);
    lv_obj_set_pos(scr->switch_4, 355, 140);
    lv_obj_set_size(scr->switch_4, 50, 26);

    // Set style of scr->switch_4
    lv_obj_set_style_bg_color(scr->switch_4, lv_color_hex(0x8fc7fe), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(scr->switch_4, lv_color_hex(0xaaffff), LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Init scr->label_1
    scr->label_1 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_1, "空调");
    lv_label_set_long_mode(scr->label_1, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_1, 98, 63);
    lv_obj_set_size(scr->label_1, 40, 26);

    // Set style of scr->label_1
    lv_obj_set_style_text_font(scr->label_1, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_3
    scr->label_3 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_3, "紫外线消毒");
    lv_label_set_long_mode(scr->label_3, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_3, 76, 144);
    lv_obj_set_size(scr->label_3, 80, 21);

    // Set style of scr->label_3
    lv_obj_set_style_text_font(scr->label_3, fs_droidsansfallback_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_4
    scr->label_4 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_4, "排气扇");
    lv_label_set_long_mode(scr->label_4, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_4, 282, 62);
    lv_obj_set_size(scr->label_4, 61, 32);

    // Set style of scr->label_4
    lv_obj_set_style_text_font(scr->label_4, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->label_5
    scr->label_5 = lv_label_create(scr->obj);
    lv_label_set_text(scr->label_5, "门");
    lv_label_set_long_mode(scr->label_5, LV_LABEL_LONG_WRAP);
    lv_obj_set_pos(scr->label_5, 302, 141);
    lv_obj_set_size(scr->label_5, 28, 21);

    // Set style of scr->label_5
    lv_obj_set_style_text_font(scr->label_5, fs_droidsansfallback_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Init scr->button_1
    scr->button_1 = lv_btn_create(scr->obj);
    lv_obj_t *button_1_label = lv_label_create(scr->button_1);
    lv_label_set_text(button_1_label, "点击进入 数据界面");
    lv_obj_align(button_1_label, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_pos(scr->button_1, 147, 207);
    lv_obj_set_size(scr->button_1, 184, 43);

    // Set style of scr->button_1
    lv_obj_set_style_bg_color(scr->button_1, lv_color_hex(0xf2fbff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(scr->button_1, fs_droidsansfallback_16, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(scr->button_1, lv_color_hex(0x0065c4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(scr->button_1, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(scr->button_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Set event handler of scr->button_1
    lv_obj_add_event_cb(scr->button_1, start_page_button_1_clicked, LV_EVENT_CLICKED, NULL);

    lv_obj_add_event_cb(scr->switch_1, switch_event_cb, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)1);
    lv_obj_add_event_cb(scr->switch_2, switch_event_cb, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)2);
    lv_obj_add_event_cb(scr->switch_3, switch_event_cb, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)3);
    lv_obj_add_event_cb(scr->switch_4, switch_event_cb, LV_EVENT_VALUE_CHANGED, (void *)(intptr_t)4);


}


