/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#include "ui_init.h"
#include "ui_util.h"
#include "aic_ui.h"
#include "custom/custom.h"

ui_manager_t ui_manager;

lv_font_t *fs_droidsansfallback_13;
lv_font_t *fs_droidsansfallback_20;
lv_font_t *fs_droidsansfallback_15;
lv_font_t *fs_droidsansfallback_16;
lv_font_t *fs_droidsansfallback_18;

void ui_init(void)
{
    fs_droidsansfallback_13 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 13);
    fs_droidsansfallback_20 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 20);
    fs_droidsansfallback_15 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 15);
    fs_droidsansfallback_16 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 16);
    fs_droidsansfallback_18 = ui_font_init(LVGL_FONT_PATH(DroidSansFallback.ttf), 18);
    if (!fs_droidsansfallback_13) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_13");
    	return;
    }
    if (!fs_droidsansfallback_20) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_20");
    	return;
    }
    if (!fs_droidsansfallback_15) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_15");
    	return;
    }
    if (!fs_droidsansfallback_16) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_16");
    	return;
    }
    if (!fs_droidsansfallback_18) {
    	LV_LOG_ERROR("Failed to init fs_droidsansfallback_18");
    	return;
    }

    // auto delete screen
    ui_manager_init(&ui_manager, true);

    start_page_create(&ui_manager);
    lv_scr_load(start_page_get(&ui_manager)->obj);

    // custom code
    custom_init();
}
