/*
 * Copyright (C) 2026 ArtInChip Technology Co., Ltd.
 *
 * This file was generated by AiUIBuilder
 * AiUIBuilder version: v2.0.2
 */

#ifndef _UI_OBJECTS
#define _UI_OBJECTS

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "lv_conf_custom.h"

#define CONN(x, y) x#y

#define LVGL_UI_BUILDER_FONT    LVGL_STORAGE_PATH"/font/"
#define LVGL_UI_BUILDER_IMAGE   "L:"LVGL_STORAGE_PATH"/image/"

#define LVGL_FONT_PATH(y)  CONN(LVGL_UI_BUILDER_FONT,  y)
#define LVGL_IMAGE_PATH(y) CONN(LVGL_UI_BUILDER_IMAGE, y)



typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_2;
    lv_obj_t *label_1;
    lv_obj_t *label_2;
    lv_obj_t *label_3;
    lv_obj_t *label_4;
    lv_obj_t *label_5;
    lv_obj_t *label_6;
    lv_obj_t *label_7;
    lv_obj_t *button_1;
} screen_t;

typedef struct {
    lv_obj_t *obj;
    lv_obj_t *image_1;
    lv_obj_t *switch_1;
    lv_obj_t *switch_2;
    lv_obj_t *switch_3;
    lv_obj_t *switch_4;
    lv_obj_t *label_1;
    lv_obj_t *label_3;
    lv_obj_t *label_4;
    lv_obj_t *label_5;
    lv_obj_t *button_1;
} start_page_t;


typedef struct {
    bool auto_del;
    screen_t screen;
    start_page_t start_page;

} ui_manager_t;

static inline void ui_manager_init(ui_manager_t *ui, bool auto_del)
{
    memset(ui, 0 , sizeof(ui_manager_t));
    ui->auto_del = auto_del;
}

static inline screen_t *screen_get(ui_manager_t *ui)
{
    return &ui->screen;
}

static inline start_page_t *start_page_get(ui_manager_t *ui)
{
    return &ui->start_page;
}


void screen_create(ui_manager_t *ui);
void start_page_create(ui_manager_t *ui);


extern lv_font_t *fs_droidsansfallback_13;
extern lv_font_t *fs_droidsansfallback_20;
extern lv_font_t *fs_droidsansfallback_15;
extern lv_font_t *fs_droidsansfallback_16;
extern lv_font_t *fs_droidsansfallback_18;


extern ui_manager_t ui_manager;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif // _UI_OBJECTS
